# reports/report_generator.py
# PDF aur Markdown reports generate karta hai

import json
import os
from datetime import datetime
from pathlib import Path
from loguru import logger


class ReportGenerator:
    """
    Scan results se professional reports banata hai.
    
    Formats:
    - Markdown — GitHub mein achha dikhta hai, PR comments ke liye
    - HTML — browser mein open karo, print karo PDF ke roop mein
    - JSON — machine-readable, dusre tools ke saath integration
    """

    def __init__(self, output_dir: str = "reports/output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_markdown(self, scan_result: dict, output_file: str = None) -> str:
        """Complete Markdown report generate karo."""
        
        scan_id    = scan_result.get("scan_id", "unknown")
        risk_level = scan_result.get("risk_level", "UNKNOWN")
        counts     = scan_result.get("counts", {})
        findings   = scan_result.get("findings", [])
        branch     = scan_result.get("branch", "N/A")
        commit     = str(scan_result.get("commit_sha", "N/A"))[:8]
        duration   = scan_result.get("duration_ms", 0)

        risk_emoji = {"PASS": "✅", "FAIL": "❌", "WARN": "⚠️"}.get(risk_level, "❓")

        lines = [
            "# 🛡️ DevSecOps Security Report",
            "",
            f"> **Result: {risk_emoji} {risk_level}**",
            "",
            "## Scan Information",
            "",
            f"| Field | Value |",
            f"|-------|-------|",
            f"| Scan ID | `{scan_id}` |",
            f"| Date | {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} |",
            f"| Branch | `{branch}` |",
            f"| Commit | `{commit}` |",
            f"| Duration | {duration}ms |",
            f"| Total Findings | {sum(counts.values())} |",
            "",
            "## Severity Summary",
            "",
            "```",
            f"🔴 Critical : {'█' * min(counts.get('critical',0), 20)} {counts.get('critical',0)}",
            f"🟠 High     : {'█' * min(counts.get('high',0), 20)} {counts.get('high',0)}",
            f"🟡 Medium   : {'█' * min(counts.get('medium',0), 20)} {counts.get('medium',0)}",
            f"🟢 Low      : {'█' * min(counts.get('low',0), 20)} {counts.get('low',0)}",
            "```",
            "",
        ]

        # Findings detail
        by_severity = {}
        for f in findings:
            sev = f.get("severity", "info").lower()
            by_severity.setdefault(sev, []).append(f)

        for sev, emoji in [("critical","🔴"),("high","🟠"),("medium","🟡"),("low","🟢")]:
            sev_findings = by_severity.get(sev, [])
            if not sev_findings:
                continue
            
            lines.append(f"## {emoji} {sev.capitalize()} ({len(sev_findings)})")
            lines.append("")
            
            for i, f in enumerate(sev_findings[:15], 1):
                lines.append(f"<details>")
                lines.append(f"<summary><strong>#{i} {f.get('vuln_type','Unknown')} — CVSS {f.get('cvss_score',0):.1f}</strong></summary>")
                lines.append("")
                lines.append(f"**Scanner:** {f.get('scanner','N/A')}  ")
                lines.append(f"**File:** `{f.get('file_path','N/A')}` line {f.get('line_number','N/A')}  ")
                lines.append(f"**Description:** {f.get('description','')[:400]}  ")
                lines.append(f"**Remediation:** {f.get('remediation','')[:300]}  ")
                lines.append("")
                lines.append(f"</details>")
                lines.append("")

        # Tool counts
        tool_counts = scan_result.get("tool_counts", {})
        if tool_counts:
            lines.append("## Tool Breakdown")
            lines.append("")
            lines.append("| Tool | Findings |")
            lines.append("|------|----------|")
            for tool, info in tool_counts.items():
                if isinstance(info, dict):
                    total = sum(v for v in info.values() if isinstance(v, int))
                    lines.append(f"| {tool} | {total} |")
                else:
                    lines.append(f"| {tool} | {info} |")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by [DevSecOps Pipeline Orchestrator](https://github.com/yourusername/devsecops-pipeline-orchestrator)*")

        content = "\n".join(lines)

        # File mein save karo agar path diya gaya
        if output_file:
            output_path = self.output_dir / output_file
            output_path.write_text(content, encoding="utf-8")
            logger.info(f"Markdown report saved: {output_path}")

        return content

    def generate_json_summary(self, scan_result: dict, output_file: str = None) -> dict:
        """Clean JSON summary generate karo — CI/CD ke liye."""
        
        findings = scan_result.get("findings", [])
        counts   = scan_result.get("counts", {})
        
        summary = {
            "schema_version": "1.0",
            "scan_id":    scan_result.get("scan_id"),
            "timestamp":  datetime.utcnow().isoformat(),
            "branch":     scan_result.get("branch"),
            "commit_sha": scan_result.get("commit_sha"),
            "result": {
                "risk_level":  scan_result.get("risk_level"),
                "risk_score":  scan_result.get("risk_score", 0),
                "should_fail": scan_result.get("risk_level") == "FAIL",
            },
            "counts": counts,
            "total_findings": sum(counts.values()),
            "top_findings": [
                {
                    "severity":    f.get("severity"),
                    "cvss_score":  f.get("cvss_score"),
                    "scanner":     f.get("scanner"),
                    "vuln_type":   f.get("vuln_type"),
                    "file_path":   f.get("file_path"),
                    "line_number": f.get("line_number"),
                }
                for f in sorted(
                    findings,
                    key=lambda x: x.get("cvss_score", 0),
                    reverse=True
                )[:20]  # Top 20 most critical
            ],
            "tool_counts": scan_result.get("tool_counts", {}),
            "duration_ms": scan_result.get("duration_ms", 0),
        }

        if output_file:
            output_path = self.output_dir / output_file
            output_path.write_text(
                json.dumps(summary, indent=2, ensure_ascii=False),
                encoding="utf-8"
            )
            logger.info(f"JSON report saved: {output_path}")

        return summary