# api/routes/reports.py
# Report generation endpoints
# PDF, Markdown, HTML reports generate karta hai

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse, HTMLResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc
import json
import os
import tempfile
from datetime import datetime
from loguru import logger

from ..database import get_db, ScanResult

router = APIRouter()


@router.get("/{scan_id}/markdown")
async def get_markdown_report(scan_id: str, db: AsyncSession = Depends(get_db)):
    """Ek scan ka Markdown report generate karo."""
    scan = await db.get(ScanResult, scan_id)
    if not scan:
        raise HTTPException(status_code=404, detail="Scan nahi mila")

    findings = scan.findings_json or []
    
    # Findings ko severity ke hisaab se group karo
    by_severity = {"critical": [], "high": [], "medium": [], "low": [], "info": []}
    for f in findings:
        sev = f.get("severity", "info").lower()
        if sev in by_severity:
            by_severity[sev].append(f)

    # Risk level emoji
    risk_emoji = {
        "PASS": "✅", "FAIL": "❌", "WARN": "⚠️", "RUNNING": "🔄"
    }.get(scan.risk_level, "❓")

    # Markdown string banao
    lines = [
        f"# 🛡️ Security Scan Report",
        f"",
        f"**Scan ID:** `{scan.id}`  ",
        f"**Date:** {scan.created_at.strftime('%Y-%m-%d %H:%M UTC') if scan.created_at else 'N/A'}  ",
        f"**Branch:** `{scan.branch}`  ",
        f"**Commit:** `{scan.commit_sha[:8] if scan.commit_sha else 'N/A'}`  ",
        f"**Triggered by:** {scan.triggered_by}  ",
        f"",
        f"## {risk_emoji} Result: {scan.risk_level}",
        f"",
        f"| Severity | Count |",
        f"|----------|-------|",
        f"| 🔴 Critical | {scan.count_critical} |",
        f"| 🟠 High | {scan.count_high} |",
        f"| 🟡 Medium | {scan.count_medium} |",
        f"| 🟢 Low | {scan.count_low} |",
        f"",
    ]

    # Har severity ka detail section
    for sev_label, sev_key, emoji in [
        ("Critical", "critical", "🔴"),
        ("High", "high", "🟠"),
        ("Medium", "medium", "🟡"),
        ("Low", "low", "🟢"),
    ]:
        sev_findings = by_severity[sev_key]
        if not sev_findings:
            continue
        
        lines.append(f"## {emoji} {sev_label} Findings ({len(sev_findings)})")
        lines.append("")
        
        for i, f in enumerate(sev_findings[:20], 1):  # Max 20 per severity
            lines.append(f"### {i}. {f.get('vuln_type', 'Unknown')}")
            lines.append(f"- **Scanner:** {f.get('scanner', 'N/A')}")
            lines.append(f"- **File:** `{f.get('file_path', 'N/A')}`:{f.get('line_number', 'N/A')}")
            lines.append(f"- **CVSS:** {f.get('cvss_score', 0):.1f}")
            lines.append(f"- **Description:** {f.get('description', '')[:200]}")
            lines.append(f"- **Fix:** {f.get('remediation', '')[:200]}")
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by DevSecOps Pipeline Orchestrator on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*")

    return {"scan_id": scan_id, "format": "markdown", "content": "\n".join(lines)}


@router.get("/{scan_id}/html", response_class=HTMLResponse)
async def get_html_report(scan_id: str, db: AsyncSession = Depends(get_db)):
    """Browser mein directly open hone wala HTML report."""
    scan = await db.get(ScanResult, scan_id)
    if not scan:
        raise HTTPException(status_code=404, detail="Scan nahi mila")

    findings = scan.findings_json or []
    
    risk_colors = {
        "PASS": "#00CC44", "FAIL": "#FF4B4B", "WARN": "#FFD700", "RUNNING": "#4488FF"
    }
    risk_color = risk_colors.get(scan.risk_level, "#888888")

    # Findings rows banao
    rows = ""
    for f in findings:
        sev = f.get("severity", "info")
        sev_colors = {
            "critical": "#FF4B4B", "high": "#FF8C00",
            "medium": "#FFD700", "low": "#00CC44", "info": "#888888"
        }
        color = sev_colors.get(sev, "#888888")
        rows += f"""
        <tr>
            <td><span style="color:{color};font-weight:bold">{sev.upper()}</span></td>
            <td>{f.get('scanner','')}</td>
            <td><code>{f.get('file_path','')[:60]}</code>:{f.get('line_number','')}</td>
            <td>{f.get('cvss_score', 0):.1f}</td>
            <td>{f.get('description','')[:150]}</td>
        </tr>
        """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Security Report — {scan.id[:8]}</title>
<style>
  body {{ font-family: -apple-system, sans-serif; max-width: 1200px; margin: 0 auto; padding: 2rem; background: #0d1117; color: #c9d1d9; }}
  h1 {{ color: #58a6ff; }}
  .badge {{ display: inline-block; padding: 4px 12px; border-radius: 20px; font-weight: bold; color: white; background: {risk_color}; }}
  .metrics {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin: 2rem 0; }}
  .metric {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1rem; text-align: center; }}
  .metric-num {{ font-size: 2rem; font-weight: bold; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 2rem; }}
  th {{ background: #161b22; padding: 10px; text-align: left; border-bottom: 2px solid #30363d; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #21262d; font-size: 13px; }}
  code {{ background: #161b22; padding: 2px 6px; border-radius: 4px; font-size: 12px; }}
  tr:hover {{ background: #161b22; }}
</style>
</head>
<body>
<h1>🛡️ Security Scan Report</h1>
<p>
  Scan: <code>{scan.id}</code> &nbsp;|&nbsp;
  Branch: <code>{scan.branch}</code> &nbsp;|&nbsp;
  Commit: <code>{(scan.commit_sha or 'N/A')[:8]}</code> &nbsp;|&nbsp;
  <span class="badge">{scan.risk_level}</span>
</p>
<div class="metrics">
  <div class="metric"><div class="metric-num" style="color:#FF4B4B">{scan.count_critical}</div><div>Critical</div></div>
  <div class="metric"><div class="metric-num" style="color:#FF8C00">{scan.count_high}</div><div>High</div></div>
  <div class="metric"><div class="metric-num" style="color:#FFD700">{scan.count_medium}</div><div>Medium</div></div>
  <div class="metric"><div class="metric-num" style="color:#00CC44">{scan.count_low}</div><div>Low</div></div>
</div>
<table>
<thead><tr><th>Severity</th><th>Scanner</th><th>Location</th><th>CVSS</th><th>Description</th></tr></thead>
<tbody>{rows}</tbody>
</table>
<hr style="border-color:#30363d;margin-top:3rem">
<p style="color:#6e7681;font-size:12px">Generated by DevSecOps Pipeline Orchestrator — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>
</body>
</html>"""

    return HTMLResponse(content=html)


@router.get("/latest/summary")
async def get_latest_summary(db: AsyncSession = Depends(get_db)):
    """Sabse nayi scan ka quick summary."""
    result = await db.execute(
        select(ScanResult)
        .where(ScanResult.risk_level != "RUNNING")
        .order_by(desc(ScanResult.created_at))
        .limit(1)
    )
    scan = result.scalar_one_or_none()
    
    if not scan:
        return {"message": "Abhi tak koi scan nahi hua"}
    
    return {
        "scan_id":    scan.id,
        "risk_level": scan.risk_level,
        "counts": {
            "critical": scan.count_critical,
            "high":     scan.count_high,
            "medium":   scan.count_medium,
        },
        "created_at": scan.created_at.isoformat() if scan.created_at else None,
    }